"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
$c\
$cmake\
$time\
$cmd_duration\
$status\
$line_break\
$character
"""

palette = "rose-pine-moon"

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'

[os]
disabled = false
style = "fg:love"
format = '[$symbol]($style)'


[os.symbols]
CachyOS = "  "
Arch = " 󰣇 "

[username]
show_always = true
style_user = "fg:color_username"
style_root = "bold fg:iris"
format = '[ $user ]($style)'

[directory]
truncation_length = 3
truncate_to_repo = true
format = '[ $path ]($style)'
style = "fg:pine"
read_only_style = "fg:pine"
repo_root_style = "bold fg:pine"
read_only = " "
truncation_symbol = ".../"
home_symbol = "~"

[git_branch]
symbol = ""
style = "fg:foam"
format = '[( $symbol $branch )]($style)'
only_attached = true
ignore_branches = []
truncation_length = 25
truncation_symbol = "..."
always_show_remote = false
disabled = false

[git_commit]
style = "fg:foam"
format = "[(( $tag)( @$hash) )]($style)"
commit_hash_length = 7
only_detached = true
tag_symbol = "󰓼 "
tag_disabled = false
disabled = false

[git_status]
style = "fg:color_git"
format = '[($ahead_behind )($all_status )]($style)'
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
ignore_submodules = false
disabled = false

[git_metrics]
format = '[(([+$added]($added_style))([-$deleted]($deleted_style)) )](fg:color_git)'
added_style = "fg:love"
deleted_style = "fg:love"
only_nonzero_diffs = true
disabled = false

[git_state]
style = "fg:color_danger"
format = '[($state( $progress_current/$progress_total) )]($style bold)'
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[c]
format = '[$symbol($version(->$name) )]($style)'
version_format = '${raw}'
symbol = ' '
style = "fg:pine"

[cmake]
format = '[$symbol($version(->$name) )]($style)'
version_format = '${raw}'
symbol = ' '
style = "fg:pine"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:pine)'
error_symbol = '[❯](bold fg:love)'

[time]
disabled = false
time_format = "%R"
style = "fg:rose"
format = '[ 󰔛 $time ]($style)'

[cmd_duration]
min_time = 2000
format = '[ 󱫑 $duration ]($style)'
style = 'fg:rose'
show_milliseconds = false
disabled = false

[status]
format = '[( $symbol( $common_meaning)( $signal_name) )]($style)'
map_symbol = true
pipestatus = true
symbol = '󰅙'
success_symbol = ''
not_executable_symbol = '󰂭'
not_found_symbol = '󰍉'
sigint_symbol = '󰐊'
signal_symbol = '󱐋'
style = 'bold fg:love'
recognize_signal_code = true
